import { Entity, PrimaryKey, Property, Enum } from '@mikro-orm/decorators/legacy'
import { v4 } from 'uuid'

// Local enum copies to avoid cross-module imports (Turbopack restriction)
enum PropertyType {
  APARTAMENTO = 'apartamento',
  CASA = 'casa',
  TERRENO = 'terreno',
  COMERCIAL = 'comercial',
  OFICINA = 'oficina',
  GALPON = 'galpon',
  OTRO = 'otro',
}

enum PropertyOperation {
  VENTA = 'venta',
  ALQUILER = 'alquiler',
  VENTA_ALQUILER = 'venta_alquiler',
}

// ---------------------------------------------------------------------------
// Contact Preferences (what the contact is looking for)
// ---------------------------------------------------------------------------

@Entity({ tableName: 'contact_preferences' })
export class ContactPreferenceEntity {
  @PrimaryKey({ type: 'uuid' })
  id: string = v4()

  @Property({ type: 'text' })
  tenant_id!: string

  @Property({ type: 'text' })
  organization_id!: string

  // Link to customer_entities
  @Property({ type: 'uuid' })
  contact_id!: string

  // Search criteria
  @Enum({ items: () => PropertyType, type: 'string', length: 30, nullable: true })
  preferred_type?: PropertyType | null

  @Enum({ items: () => PropertyOperation, type: 'string', length: 20, nullable: true })
  preferred_operation?: PropertyOperation | null

  @Property({ type: 'text', length: 100, nullable: true })
  preferred_city?: string | null

  @Property({ type: 'decimal', precision: 18, scale: 2, nullable: true })
  max_budget?: string | null

  @Property({ type: 'text', length: 10, default: 'USD' })
  budget_currency: string = 'USD'

  @Property({ type: 'decimal', precision: 10, scale: 2, nullable: true })
  min_area_m2?: string | null

  @Property({ type: 'smallint', nullable: true })
  min_bedrooms?: number | null

  @Property({ type: 'smallint', nullable: true })
  min_bathrooms?: number | null

  @Property({ type: 'smallint', nullable: true })
  min_parking?: number | null

  @Property({ type: 'text', nullable: true })
  notes?: string | null

  @Property({ type: 'boolean', default: true })
  is_active: boolean = true

  @Property({ type: 'timestamptz' })
  created_at: Date = new Date()

  @Property({ type: 'timestamptz', onUpdate: () => new Date() })
  updated_at: Date = new Date()

  @Property({ type: 'timestamptz', nullable: true })
  deleted_at?: Date | null
}

// ---------------------------------------------------------------------------
// Match Results (generated by the matching engine)
// ---------------------------------------------------------------------------

@Entity({ tableName: 'match_results' })
export class MatchResultEntity {
  @PrimaryKey({ type: 'uuid' })
  id: string = v4()

  @Property({ type: 'text' })
  tenant_id!: string

  @Property({ type: 'text' })
  organization_id!: string

  @Property({ type: 'uuid' })
  contact_id!: string

  @Property({ type: 'uuid' })
  property_id!: string

  // Score 0-100
  @Property({ type: 'smallint' })
  score!: number

  // Which criteria matched (JSON)
  @Property({ type: 'jsonb', nullable: true })
  criteria_matched?: Record<string, boolean> | null

  @Property({ type: 'boolean', default: false })
  is_notified: boolean = false

  @Property({ type: 'boolean', default: false })
  is_dismissed: boolean = false

  @Property({ type: 'timestamptz' })
  created_at: Date = new Date()
}
