import { Migration } from '@mikro-orm/migrations';

export class Migration20260526092600_mfg_procurement extends Migration {

  override up(): void | Promise<void> {
    this.addSql(`create table "mfg_purchase_orders" ("id" uuid not null, "tenant_id" text not null, "organization_id" text not null, "po_number" text not null, "supplier_id" uuid not null, "supplier_name" text not null, "po_type" text not null default 'national', "status" text not null default 'draft', "currency" text not null default 'USD', "subtotal_fob" numeric(14,2) not null default '0.00', "freight_cost" numeric(14,2) not null default '0.00', "insurance_cost" numeric(14,2) not null default '0.00', "tariff_cost" numeric(14,2) not null default '0.00', "import_vat" numeric(14,2) not null default '0.00', "agency_fees" numeric(14,2) not null default '0.00', "inland_transport" numeric(14,2) not null default '0.00', "total_cif_cost" numeric(14,2) not null default '0.00', "incoterm" text null, "country_of_origin" text null, "dau_number" text null, "customs_agent" text null, "estimated_ship_date" date null, "actual_ship_date" date null, "estimated_arrival_port" date null, "actual_arrival_port" date null, "estimated_customs_clearance" date null, "actual_customs_clearance" date null, "estimated_warehouse_arrival" date null, "actual_warehouse_arrival" date null, "bcv_rate_at_order" numeric(12,4) null, "bcv_rate_at_arrival" numeric(12,4) null, "notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, primary key ("id"));`);

    this.addSql(`create table "mfg_purchase_order_lines" ("id" uuid not null, "tenant_id" text not null, "organization_id" text not null, "po_id" uuid not null, "line_number" smallint not null, "material_id" uuid not null, "material_code" text not null, "material_name" text not null, "quantity" numeric(14,4) not null, "uom" text not null, "unit_price" numeric(12,6) not null, "total_price" numeric(14,2) not null, "unit_cif_cost" numeric(14,6) null, "quantity_received" numeric(14,4) not null default '0.0000', "received_date" date null, "requisition_id" uuid null, "created_at" timestamptz not null, "updated_at" timestamptz not null, primary key ("id"));`);

    this.addSql(`create table "mfg_suppliers" ("id" uuid not null, "tenant_id" text not null, "organization_id" text not null, "supplier_code" text not null, "name" text not null, "country" text null, "supplier_type" text not null default 'national', "contact_name" text null, "contact_email" text null, "contact_phone" text null, "payment_terms" text not null default 'advance', "currency" text not null default 'USD', "avg_lead_time_days" numeric(8,1) null, "on_time_delivery_pct" numeric(5,2) null, "total_orders" int not null default 0, "is_active" boolean not null default true, "notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, primary key ("id"));`);
  }

}
