import { Migration } from '@mikro-orm/migrations';

export class Migration20260526092600_mfg_maintenance extends Migration {

  override up(): void | Promise<void> {
    this.addSql(`create table "mfg_equipment" ("id" uuid not null, "tenant_id" text not null, "organization_id" text not null, "equipment_code" text not null, "name" text not null, "description" text null, "brand" text null, "model" text null, "serial_number" text null, "manufacture_year" smallint null, "work_center_id" uuid null, "work_center_name" text null, "status" text not null default 'operational', "last_overhaul_date" date null, "next_maintenance_date" date null, "replacement_cost_usd" numeric(14,2) null, "supplier_contact" text null, "manual_document_url" text null, "criticality" text not null default 'medium', "accumulated_hours" numeric(10,2) not null default '0.00', "notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, primary key ("id"));`);

    this.addSql(`create table "mfg_maintenance_plans" ("id" uuid not null, "tenant_id" text not null, "organization_id" text not null, "equipment_id" uuid not null, "equipment_code" text not null, "plan_name" text not null, "trigger_type" text not null default 'days', "trigger_interval" numeric(10,2) not null, "last_performed_date" date null, "last_performed_hours" numeric(10,2) null, "next_due_date" date null, "next_due_hours" numeric(10,2) null, "estimated_duration_hrs" numeric(6,2) not null default '2.00', "requires_shutdown" boolean not null default false, "required_spare_parts" jsonb null, "required_technician_skill" text null, "status" text not null default 'active', "notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, primary key ("id"));`);

    this.addSql(`create table "mfg_spare_parts" ("id" uuid not null, "tenant_id" text not null, "organization_id" text not null, "part_code" text not null, "part_name" text not null, "description" text null, "equipment_ids" jsonb null, "current_stock" numeric(12,4) not null default '0.0000', "uom" text not null default 'units', "unit_cost_usd" numeric(12,4) null, "reorder_point" numeric(12,4) not null default '1.0000', "safety_stock" numeric(12,4) not null default '1.0000', "max_stock" numeric(12,4) null, "is_imported" boolean not null default false, "lead_time_days" int not null default 15, "mtbf_days" numeric(8,2) null, "supplier_id" uuid null, "supplier_name" text null, "storage_location" text null, "last_purchase_date" date null, "last_purchase_price_usd" numeric(12,4) null, "notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, primary key ("id"));`);

    this.addSql(`create table "mfg_work_orders_maint" ("id" uuid not null, "tenant_id" text not null, "organization_id" text not null, "wo_number" text not null, "equipment_id" uuid not null, "equipment_code" text not null, "equipment_name" text not null, "maintenance_plan_id" uuid null, "work_type" text not null default 'preventive', "priority" text not null default 'medium', "status" text not null default 'open', "description" text not null, "fault_description" text null, "assigned_to" uuid null, "scheduled_date" date null, "started_at" timestamptz null, "completed_at" timestamptz null, "actual_duration_hrs" numeric(6,2) null, "estimated_duration_hrs" numeric(6,2) null, "spare_parts_used" jsonb null, "total_parts_cost_usd" numeric(12,2) not null default '0.00', "work_performed" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, primary key ("id"));`);
  }

}
